### ISSUE TITLE
[Feature Request] [Notes] Add command to list all users with notes, without the notes themselves. 

### ISSUE THREAD

**Issue by cag1585** [i-am-zaidali/cray-cogs#35]
Having a list of just users and how many notes they have without needing to use reactions to scroll would be great.
This is useful for a scheduled daily post in your mod channel for who has notes. This way if something comes up later in the day they have that user already in mind.
As it is currently with `[p]allnotes` my staff will only see the first one unless they run the command themselves. (assuming they aren't on for the scheduled post).

Or maybe another option that I know would work for me is an option to make it so `allnotes` post every note at once. 1 embed, separate, I don't care.

Thanks for your time and your cog!

**Comment by i-am-zaidali** [comment]
I see the usecase. But i cant really think of a name for such a command. LMK if u have any recommendations.

**Comment by Corbin602** [comment]
I would just say `listnotes` seems to fit alright with the rest.
I think an option for `allnotes` to list each one as a separate embed may also be useful. 

Thanks for considering!

**Comment by i-am-zaidali** [comment]
> I would just say `listnotes` seems to fit alright with the rest. 
Yes it sounds good. But my cogs are so far feature locked until Red 3.5 releases so you will have to wait for this feature until then.

>I think an option for `allnotes` to list each one as a separate embed may also be useful.
I'm sorry but I won't be considering this. The reason for this is because sending one embed per user can be very spammy and lead to ratelimits. With red 3.5, I might consider adding select menus to this command to allow you to individually select each user along with having buttons to manually navigate through the pages

**Comment by Corbin602** [comment]
Okay, understood. Thank you!

**Comment by i-am-zaidali** [comment]
@cag1585 as mentioned above this has been done. I was free and 3.5 is still a while away so here u go!
